version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3390:3306"

  api:
    build: .
    restart: always
    depends_on:
      - db  
    env_file: .env
    volumes:
      - ./uploaded_files:/app/uploaded_files
    ports:
      - "8989:8000"

volumes:
  mysql_data: